### ISSUE TITLE
Add support for Gravity Forms columns

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/codepress-admin-columns#22]
Suggested feature: Support for Gravityt Forms columns.

suggested by: will at collectorsbluebook.com

**Comment by 13pixlar** [comment]
+1

**Comment by nineyards** [comment]
Yes, me too. Would be awsome!

**Comment by tobiasschutter** [comment]
@nineyards  Could you give some examples on what columns you would like to have supported?

**Comment by nineyards** [comment]
@tobiasschutter Absolutely!

It would be awesome to be able to inline edit entries in the Gravity Forms submission list. This would save lots of time since the current way to edit entries involves:

* first clicking "View" on an entry, 
* wait for the entry to load and then click "Edit"
* make the edit and hit "Save"
* wait for save and then click a link to return to the entry list

As a start, text fields, selects and radio buttons would be nice to have. If you need more info or some test I´d be happy to help.

**Comment by tobiasschutter** [comment]
I had another look at GF, but unfortunately Gravity Forms doesn't use the WordPress native WP_List_Table class, but has it's own custom table. Unless they start using WP native tables, this won't work :(

**Comment by 13pixlar** [comment]
Thats too bad. I guess RocketGenius won't be interested in modifying their code...
